# Generated by Django 3.2.14 on 2023-05-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodels',
            name='sex',
            field=models.IntegerField(choices=[(0, '女'), (1, '男')], default=1),
        ),
    ]
