# Generated by Django 3.2.14 on 2023-05-16 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glf', '0002_usermodels_sex'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodels',
            table='user',
        ),
    ]
